version: "3.7"

services:
  nginx:
    build: .docker/nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - .docker/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/log:/var/log/nginx
      - ~/.ssl:/etc/nginx/ssl
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    build: .docker/php
    container_name: php
    ports:
      - 9000:9000
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - .docker/mysql/data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
    restart: always
